### ISSUE TITLE
Labels of MIMIC CXR

### ISSUE THREAD

**Issue by Guoli-w** [Lab-LVM/ADNet#1]
Thank you for your detailed presentation.
I am having a hard time getting the label situation for the MIMIC CXR, can you help me?
Can I get these 4 files below?
![53c2781e66dde086c19f5bee6250b70](https://github.com/user-attachments/assets/6966657d-4950-451d-9149-310c42539247)

**Comment by hankyul2** [comment]
Hi @Guoli-w 

First of all, thank you for paying attention to our project.

You can generate the mentioned JSON files following [this step](https://github.com/Lab-LVM/ADNet/blob/main/misc/mimic-cxr.md). We update the Jupyter notebook we use for pre-processing dataset files. We think you can easily get such JSON files following the guidelines we provide. For your information, the MIMIC-CXR rule of agreement prohibits data sharing with another person. Sorry for not sharing JSON files with you.

If you have more questions, please ask us without hesitation.

Thank you
Hankyul
